[workspace]
members = ["proc_macros", "term_render"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.47.1", features = ["io-util", "macros", "rt-multi-thread", "io-std", "time"] }
term_render = { path = "term_render" }