[package]
name = "term_render_example"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["io-util", "macros", "rt-multi-thread", "io-std", "time"] }
term_render = { path = "term_render" }