[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies]
term_render = { path = "../term_render" }
tokio = { version = "1.47.1", features = ["io-util", "macros", "rt-multi-thread", "io-std", "time"] }